<div  align='center'><img src='https://s3.amazonaws.com/weclouddata/images/logos/wcd_logo_new_2.png' width='25%'></div >

<h1 align="center"> Pandas Intro Exercises </h1>
<h2 align="center"> (Lab Version) </h2>

</font></b></p>

<br>
<center align="center"> Designed by: </center>
<center align="center"> WeCloudData Academy </center>

# Data Exploration.

> Dataset can be downloaded from here:
- https://s3.amazonaws.com/weclouddata/datasets/genai/ml_fundamentals/telecom.csv

In [41]:
!wget https://s3.amazonaws.com/weclouddata/datasets/genai/ml_fundamentals/telecom.csv

--2026-05-12 10:58:39--  https://s3.amazonaws.com/weclouddata/datasets/genai/ml_fundamentals/telecom.csv
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.234.32, 16.15.228.212, 16.182.102.176, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.234.32|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 977501 (955K) [text/csv]
Saving to: ‘telecom.csv.4’

telecom.csv.4       100%[===================>] 954.59K  --.-KB/s    in 0.1s

2026-05-12 10:58:39 (6.93 MB/s) - ‘telecom.csv.4’ saved [977501/977501]

> ### Read in the telecom churn dataset.
>    - Check for the size of the dataset.
>    - Check for null values.

> ### 1. Check for how many numerical and categorical there are in the dataset.
>    - Use the select_dtypes() method. [select_dtypes](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.select_dtypes.html)

In [42]:
import pandas as pd

df = pd.read_csv('telecom.csv')
print("Dataset loaded ✓")

Dataset loaded ✓

In [43]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [44]:
print("Shape:", df.shape)
print(f"Rows: {df.shape[0]:,}  |  Columns: {df.shape[1]}")

# Null values
print("\n--- Null Values ---")
print(df.isnull().sum())
print(f"\nTotal nulls: {df.isnull().sum().sum()}")

Shape: (7043, 21)
Rows: 7,043  |  Columns: 21

--- Null Values ---
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

Total nulls: 0

In [45]:
# Numerical columns
numerical = df.select_dtypes(include=['number'])
print(f"Numerical columns ({len(numerical.columns)}):")
print(numerical.columns.tolist())

# Categorical columns
categorical = df.select_dtypes(include=['object', 'category'])
print(f"\nCategorical columns ({len(categorical.columns)}):")
print(categorical.columns.tolist())

print(f"\nSummary: {len(numerical.columns)} numerical, {len(categorical.columns)} categorical")

Numerical columns (3):
['SeniorCitizen', 'tenure', 'MonthlyCharges']

Categorical columns (18):
['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'TotalCharges', 'Churn']

Summary: 3 numerical, 18 categorical

> ### 2. Map the following columns `Partner`, `Dependents`, `PhoneService`
>    - For each of the columns listed above, map `Yes` to `1`, `No` to `0`.

In [46]:
# for loop
# map
#replace

In [47]:
# Columns to map
cols = ['Partner', 'Dependents', 'PhoneService']

# Map Yes → 1, No → 0
df[cols] = df[cols].replace({'Yes': 1, 'No': 0})

# Verify the result
print(df[cols].head(5))
print("\nUnique values after mapping:")
for col in cols:
    print(f"  {col}: {sorted(df[col].unique())}")

   Partner  Dependents  PhoneService
0        1           0             0
1        0           0             1
2        0           0             1
3        0           0             0
4        0           0             1

Unique values after mapping:
  Partner: [np.int64(0), np.int64(1)]
  Dependents: [np.int64(0), np.int64(1)]
  PhoneService: [np.int64(0), np.int64(1)]

/tmp/ipykernel_1731/3947991343.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[cols] = df[cols].replace({'Yes': 1, 'No': 0})

> ### 3. Convert the data type of the `TotalCharges` column to the float data type.
>    - Replace missing values with 0

In [48]:
# Step 1: Convert to numeric (coerce turns invalid strings into NaN)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Step 2: Replace NaN with 0
df['TotalCharges'] = df['TotalCharges'].fillna(0)

# Verify
print("dtype :", df['TotalCharges'].dtype)
print("Nulls :", df['TotalCharges'].isnull().sum())
print(df['TotalCharges'].head(5))

dtype : float64
Nulls : 0
0      29.85
1    1889.50
2     108.15
3    1840.75
4     151.65
Name: TotalCharges, dtype: float64

> ### 4. Return the top 10 customers with the highest `TotalCharges`.
>    - a) How many of these customers have multiple lines?
>    - b) How many of these customers have subscribed to `PaperlessBilling`?

In [49]:
# Get top 10 customers by TotalCharges
top10 = df.nlargest(10, 'TotalCharges')

print(top10[['customerID', 'TotalCharges', 'MultipleLines', 'PaperlessBilling']])

      customerID  TotalCharges MultipleLines PaperlessBilling
4610  2889-FPWRM       8684.80           Yes              Yes
4586  7569-NMZYQ       8672.45           Yes              Yes
6768  9739-JLPQJ       8670.10           Yes               No
5347  9788-HNGUT       8594.40           Yes              Yes
2187  8879-XUAHX       8564.75           Yes              Yes
6118  9924-JPRMC       8547.15           Yes              Yes
5558  0675-NCDYU       8543.25           Yes              Yes
2368  6650-BWFRT       8529.50           Yes              Yes
2603  0164-APGRB       8496.70           Yes              Yes
2025  1488-PBLJN       8477.70           Yes              Yes

In [50]:
# a) How many have multiple lines?
multiple_lines = top10[top10['MultipleLines'] == 'Yes']
print(f"Customers with Multiple Lines: {len(multiple_lines)}")
print(multiple_lines[['customerID', 'TotalCharges', 'MultipleLines']])

Customers with Multiple Lines: 10
      customerID  TotalCharges MultipleLines
4610  2889-FPWRM       8684.80           Yes
4586  7569-NMZYQ       8672.45           Yes
6768  9739-JLPQJ       8670.10           Yes
5347  9788-HNGUT       8594.40           Yes
2187  8879-XUAHX       8564.75           Yes
6118  9924-JPRMC       8547.15           Yes
5558  0675-NCDYU       8543.25           Yes
2368  6650-BWFRT       8529.50           Yes
2603  0164-APGRB       8496.70           Yes
2025  1488-PBLJN       8477.70           Yes

In [51]:
# b) How many subscribed to PaperlessBilling?
paperless = top10[top10['PaperlessBilling'] == 'Yes']
print(f"Customers with PaperlessBilling: {len(paperless)}")
print(paperless[['customerID', 'TotalCharges', 'PaperlessBilling']])

Customers with PaperlessBilling: 9
      customerID  TotalCharges PaperlessBilling
4610  2889-FPWRM       8684.80              Yes
4586  7569-NMZYQ       8672.45              Yes
5347  9788-HNGUT       8594.40              Yes
2187  8879-XUAHX       8564.75              Yes
6118  9924-JPRMC       8547.15              Yes
5558  0675-NCDYU       8543.25              Yes
2368  6650-BWFRT       8529.50              Yes
2603  0164-APGRB       8496.70              Yes
2025  1488-PBLJN       8477.70              Yes

> ### 5. Return the top 100 customers with the highest `MonthlyCharges`
>    - a) What was the most frequent `InternetService` used by these customers?
>    - b) How many of these customers churned? (Return the results as a percentage)
>        - **hint:** `normalize` parameter in value_counts() method.

In [52]:
# Get top 100 customers by MonthlyCharges
top100 = df.nlargest(100, 'MonthlyCharges')

print(top100[['customerID', 'MonthlyCharges', 'InternetService', 'Churn']].head(10))

      customerID  MonthlyCharges InternetService Churn
4586  7569-NMZYQ          118.75     Fiber optic    No
2115  8984-HPEMB          118.65     Fiber optic    No
3894  5989-AXPUC          118.60     Fiber optic    No
4804  5734-EJKXG          118.60     Fiber optic    No
5127  8199-ZLLSA          118.35     Fiber optic   Yes
6118  9924-JPRMC          118.20     Fiber optic    No
4610  2889-FPWRM          117.80     Fiber optic   Yes
3205  3810-DVDQQ          117.60     Fiber optic    No
6768  9739-JLPQJ          117.50     Fiber optic    No
4875  2302-ANTDP          117.45     Fiber optic   Yes

In [53]:
# a) Most frequent InternetService
internet_counts = top100['InternetService'].value_counts()
print("InternetService distribution:\n", internet_counts)
print(f"\nMost frequent: {internet_counts.idxmax()} ({internet_counts.max()} customers)")

InternetService distribution:
 InternetService
Fiber optic    100
Name: count, dtype: int64

Most frequent: Fiber optic (100 customers)

In [54]:
# b) Churn percentage using normalize=True
churn_pct = top100['Churn'].value_counts(normalize=True) * 100
print("Churn breakdown (%):\n", churn_pct.round(2))

Churn breakdown (%):
 Churn
No     92.0
Yes     8.0
Name: proportion, dtype: float64

> ### 6. Create a new column named `loyalty`. This column will contain the following:
> Iterate through the `tenure` column and store the following elements in a list. Assign the list to the column `loyalty`:
>    - If the customers tenure is below 12, flag it as `Bronze`.
>    - If the customers tenure is between 12 and 24, flag it as `Silver`.
>    - If the customers tenure is above 24, flag it as `Gold`.

In [55]:
df['tenure']

0        1
1       34
2        2
3       45
4        2
        ..
7038    24
7039    72
7040    11
7041     4
7042    66
Name: tenure, Length: 7043, dtype: int64

In [56]:
loyalty = []

for t in df['tenure']:
    if t < 12:
        loyalty.append('Bronze')
    elif t <= 24:
        loyalty.append('Silver')
    else:
        loyalty.append('Gold')

df['loyalty'] = loyalty

In [57]:
df[['tenure', 'loyalty']].head()

   tenure loyalty
0       1  Bronze
1      34    Gold
2       2  Bronze
3      45    Gold
4       2  Bronze

> ### 7. Create a new column named `Customer Value`. This column will contain the following:
> Iterate through the `TotalCharges` column and store the following elements in a list. Assign the list to the column `Customer Value`:
>    - If the customers TotalCharges is below 1000, flag the customer as `low`.
>    - If the customers TotalCharges is between 1000 and 3000, flag the customer as `medium`.
>    - If the customers TotalCharges is above 3000, flag the customer as `high`.

In [58]:

# Iterate through TotalCharges and build the list
customer_value = []

for charge in df['TotalCharges']:
    if charge < 1000:
        customer_value.append('low')
    elif 1000 <= charge <= 3000:
        customer_value.append('medium')
    else:
        customer_value.append('high')

# Assign the list to the new column
df['Customer Value'] = customer_value

# Verify
print(df[['TotalCharges', 'Customer Value']].head(10))
print("\nValue counts:")
print(df['Customer Value'].value_counts())

   TotalCharges Customer Value
0         29.85            low
1       1889.50         medium
2        108.15            low
3       1840.75         medium
4        151.65            low
5        820.50            low
6       1949.40         medium
7        301.90            low
8       3046.05           high
9       3487.95           high

Value counts:
Customer Value
low       2904
high      2204
medium    1935
Name: count, dtype: int64

> ### 8. Which payment method is the most frequent?
>    - a) Use the to_dict() method to convert the output to a dictionary.
>    - b) Create a new dataframe `top_payment_method` using the dictionary generated from the previous step. Name the column `frequency`.

In [59]:
# Get value counts and find the most frequent
payment_counts = df['PaymentMethod'].value_counts()
print("Payment Method Counts:\n", payment_counts)
print(f"\nMost frequent: {payment_counts.idxmax()} ({payment_counts.max()} customers)")

Payment Method Counts:
 PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

Most frequent: Electronic check (2365 customers)

In [60]:
# a) Convert value_counts output to a dictionary
payment_dict = payment_counts.to_dict()
print(payment_dict)

{'Electronic check': 2365, 'Mailed check': 1612, 'Bank transfer (automatic)': 1544, 'Credit card (automatic)': 1522}

In [61]:
# b) Create a new dataframe from the dictionary
top_payment_method = pd.DataFrame.from_dict(
    payment_dict,
    orient='index',
    columns=['frequency']
)

print(top_payment_method)

                           frequency
Electronic check                2365
Mailed check                    1612
Bank transfer (automatic)       1544
Credit card (automatic)         1522

> ### 9. How many customers are on a One year contract and have not completed a 12 month tenure?

In [62]:
# Two conditions combined with &
mask = (df['Contract'] == 'One year') & (df['tenure'] < 12)

result = df[mask]

print(f"Count: {len(result)}")
print(result[['customerID', 'Contract', 'tenure']])

Count: 102
      customerID  Contract  tenure
40    8865-TNMNX  One year      10
146   6837-BJYDQ  One year       3
164   2907-ILJBN  One year      11
222   6469-MRVET  One year       1
323   7102-JJVTX  One year       9
...          ...       ...     ...
6556  0661-KQHNK  One year       6
6578  3898-BSJYF  One year      10
6628  9979-RGMZT  One year       7
6636  3468-DRVQJ  One year      10
6684  0305-SQECB  One year      11

[102 rows x 3 columns]

> ### 10. How many customers are on a One Year contract, are subscribed to tech support and are in the `Gold` loyalty program?

In [63]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,loyalty,Customer Value
0,7590-VHVEG,Female,0,1,0,1,0,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,Bronze,low
1,5575-GNVDE,Male,0,0,0,34,1,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.50,No,Gold,medium
2,3668-QPYBK,Male,0,0,0,2,1,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,Bronze,low
3,7795-CFOCW,Male,0,0,0,45,0,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,Gold,medium
4,9237-HQITU,Female,0,0,0,2,1,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,Bronze,low

In [64]:
# 3 conditions combined with &
mask = (
    (df['Contract']    == 'One year') &
    (df['TechSupport'] == 'Yes')      &
    (df['loyalty']     == 'Gold')
)

result = df[mask]

print(f"Count: {len(result)}")
print(result[['customerID', 'Contract', 'TechSupport', 'loyalty']])

Count: 476
      customerID  Contract TechSupport loyalty
3     7795-CFOCW  One year         Yes    Gold
32    6827-IEAUQ  One year         Yes    Gold
54    4667-QONEA  One year         Yes    Gold
57    5067-XJQFU  One year         Yes    Gold
96    9803-FTJCG  One year         Yes    Gold
...          ...       ...         ...     ...
6964  1264-FUHCX  One year         Yes    Gold
6972  6664-FPDAC  One year         Yes    Gold
6973  9972-VAFJJ  One year         Yes    Gold
6985  6967-PEJLL  One year         Yes    Gold
6996  4174-LPGTI  One year         Yes    Gold

[476 rows x 4 columns]

> ### 11. How many customers from the dataset churned? How many did not churn? (Display as a percentage)

In [65]:
# Churn percentage using normalize=True
churn_pct = df['Churn'].value_counts(normalize=True) * 100

print("Churn Distribution (%):")
print(churn_pct.round(2).to_string())

Churn Distribution (%):
Churn
No     73.46
Yes    26.54

## Exploring customers who churned.
>    - Create a dataframe for customers who churned and name the dataframe `churned`

In [66]:
# Filter only customers who churned
churned = df[df['Churn'] == 'Yes']

# Verify
print(f"Shape: {churned.shape}")
print(f"Total churned customers: {len(churned)}")
churned.head()

Shape: (1869, 23)
Total churned customers: 1869

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,loyalty,Customer Value
2,3668-QPYBK,Male,0,0,0,2,1,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,Bronze,low
4,9237-HQITU,Female,0,0,0,2,1,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,Bronze,low
5,9305-CDSKC,Female,0,0,0,8,1,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,Bronze,low
8,7892-POOKP,Female,0,1,0,28,1,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,Gold,high
13,0280-XJGEX,Male,0,0,0,49,1,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes,Gold,high

> ### 12. For customers who churned:
>    - a) What is the gender distribution?
>    - b) What is the average tenure length per `Contract`?
>    - c) For Males & Females, what is the average tenure length per `Contract` for each gender group?
>    - d) For Males & Females, what is the average tenure length per `Contract` for each gender group for customers who are on `DSL`?

In [67]:
# a) Gender distribution of churned customers
gender_dist = churned['gender'].value_counts()
print("Gender Distribution:\n", gender_dist)
print("\nAs percentage:")
print((churned['gender'].value_counts(normalize=True) * 100).round(2))

Gender Distribution:
 gender
Female    939
Male      930
Name: count, dtype: int64

As percentage:
gender
Female    50.24
Male      49.76
Name: proportion, dtype: float64

In [68]:
# b) Average tenure per Contract type
avg_tenure_contract = churned.groupby('Contract')['tenure'].mean().round(2)
print("Avg Tenure per Contract:\n", avg_tenure_contract)

Avg Tenure per Contract:
 Contract
Month-to-month    14.02
One year          44.96
Two year          61.27
Name: tenure, dtype: float64

In [69]:
# c) Average tenure per Contract grouped by gender
avg_tenure_gender = churned.groupby(['gender', 'Contract'])['tenure'].mean().round(2)
print("Avg Tenure by Gender & Contract:\n", avg_tenure_gender)

Avg Tenure by Gender & Contract:
 gender  Contract
Female  Month-to-month    13.50
        One year          44.60
        Two year          56.91
Male    Month-to-month    14.55
        One year          45.26
        Two year          64.96
Name: tenure, dtype: float64

In [70]:
# d) Filter DSL customers first, then group by gender & Contract
dsl_churned = churned[churned['InternetService'] == 'DSL']

avg_tenure_dsl = dsl_churned.groupby(['gender', 'Contract'])['tenure'].mean().round(2)
print("Avg Tenure by Gender & Contract (DSL only):\n", avg_tenure_dsl)

Avg Tenure by Gender & Contract (DSL only):
 gender  Contract
Female  Month-to-month    10.24
        One year          36.00
        Two year          64.86
Male    Month-to-month     9.08
        One year          35.68
        Two year          64.80
Name: tenure, dtype: float64

> ### 13. Senior Citizens that churned:
>    - a) Which `InternetService` brought in the most sales?
>    - b) What is the distribution of seniors from each loyalty program?
>    - c) Which `PaymentMethod` is bringing in the most sales from each loyalty program?
>    - d) How many Seniors are in the `Gold` loyalty program or are a `low` valued customer?
>    - e) Are there any Seniors that are in both the `Gold` loyalty program but considered a low valued customer?